### ISSUE TITLE
rtree.d(82,19): Error: cannot implicitly convert expression a_dataId of type const(T) to T

### ISSUE THREAD

**Issue by Robert-M-Muench** [drug007/rtree#3]
I get this error when using `RTree!(myClass, float, 2, double)` and trying to insert a node with:

``` 
// myObj is of type MyClass
foreach(myObj; ...){
  rtree.insert(min, max, myObj);
}
``` 
The problem seems to be that the const from the parameter is not reflected in the template instantiation. But when I try to use:  `RTree!(const myClass, float, 2, double)` I get a bunch of other problems origin from here:

```
...
rtree.d(125,2):        instantiated from here: Array!(const(myClass))
```

Isn't the const for insert wrong?

**Comment by drug007** [comment]
I'm not sure 100% but I think that `const` qualifier here is too restrictive. I have removed this qualifier in `fix-#3` branch. Could you test these changes?

**Comment by Robert-M-Muench** [comment]
Yes, this now works.

Why did you remove the `auto ref` too?

**Comment by drug007** [comment]
Size of `DataType` is no larger than pointer size, so there is no reason to pass it by reference.

**Comment by drug007** [comment]
Also passing by value is equal to using `const` qualifier
